
{'date': 'Mon Oct 08 2018 18:04:14.132 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 8
    Historia()
  module <module> line 6
    cenaSea = Cena(img = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/The_deep_blue_sea_%286834127561%29.jpg/800px-The_deep_blue_sea_%286834127561%29.jpg")
TypeError: 'module' object is not callable
'''},
{'date': 'Mon Oct 08 2018 18:04:32.900 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 8
    Historia()
  module <module> line 6
    CenaBeach = cena(img = "https://www.google.com.br/search?q=praia&safe=strict&rlz=1C1SQJL_pt-BRBR818&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiVv9Hu2ffdAhUC1lkKHU6VBw4Q_AUIDigB&biw=1366&bih=657#imgrc=ztCLFkXnxXHEUM:")
NameError: name 'cena' is not defined
'''},
{'date': 'Mon Oct 08 2018 18:12:31.993 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 8
    Historia()
  module <module> line 6
    CenaBeach = cena(img = "https://www.google.com.br/search?q=praia&safe=strict&rlz=1C1SQJL_pt-BRBR818&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiVv9Hu2ffdAhUC1lkKHU6VBw4Q_AUIDigB&biw=1366&bih=657#imgrc=ztCLFkXnxXHEUM:")
NameError: name 'cena' is not defined
'''},
{'date': 'Mon Oct 08 2018 18:12:32.847 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 8
    Historia()
  module <module> line 6
    CenaBeach = cena(img = "https://www.google.com.br/search?q=praia&safe=strict&rlz=1C1SQJL_pt-BRBR818&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiVv9Hu2ffdAhUC1lkKHU6VBw4Q_AUIDigB&biw=1366&bih=657#imgrc=ztCLFkXnxXHEUM:")
NameError: name 'cena' is not defined
'''},
{'date': 'Mon Oct 08 2018 18:12:36.582 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 8
    Historia()
  module <module> line 6
    CenaBeach = cena(img = "https://www.google.com.br/search?q=praia&safe=strict&rlz=1C1SQJL_pt-BRBR818&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiVv9Hu2ffdAhUC1lkKHU6VBw4Q_AUIDigB&biw=1366&bih=657#imgrc=ztCLFkXnxXHEUM:")
NameError: name 'cena' is not defined
'''},
{'date': 'Mon Oct 08 2018 18:23:07.861 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 7
  CenaTeatro=.vai()
              ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Oct 08 2018 18:26:03.805 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 7
  CenaTeatro=.vai()
              ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Oct 17 2018 17:28:33.489 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 7
  CenaTeatro=.vai()
              ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Oct 17 2018 17:35:42.751 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 6
  CenaTeatro = Cena(img = https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdPLYgHZx_3F32cbuvh1F1JCtI7wCETneHux09yVAqsmfEOX5C )
                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Oct 17 2018 18:23:08.405 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    Historia()
  module <module> line 10
    chica.entra(cenaTeatro)
NameError: name 'cenaTeatro' is not defined
'''},
{'date': 'Wed Oct 17 2018 18:24:20.746 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    Historia()
  module <module> line 10
    chica.entra(cenaTeatro)
NameError: name 'cenaTeatro' is not defined
'''},
{'date': 'Wed Oct 17 2018 18:24:52.459 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    Historia()
  module <module> line 11
    CenaTeatro.vai()
NameError: name 'CenaTeatro' is not defined
'''},
{'date': 'Fri Oct 19 2018 11:13:30.232 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 4
  Chica=
         ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Oct 19 2018 11:27:20.454 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 10
    Historia()
  module <module> line 9
    ILHA.Vai ()
AttributeError: 'Cena' object has no attribute 'Vai'
'''},
{'date': 'Fri Oct 19 2018 11:30:48.671 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 10
    Historia()
  module <module> line 9
    ILHA.Vai()
AttributeError: 'Cena' object has no attribute 'Vai'
'''},
{'date': 'Fri Oct 19 2018 11:36:18.68 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 15
    historia()
  module <module> line 6
    cenaoceano = Cena(img="https://mardehistorias.files.wordpress.com/2010/11/oceano.jpg")              
NameError: name 'Cena' is not defined
'''},
{'date': 'Fri Oct 19 2018 11:36:56.367 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 4
  Chica=
         ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Oct 19 2018 11:38:38.675 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  nemo.entra(cenaoceano)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Oct 19 2018 11:39:09.63 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 17
    Historia()
NameError: name 'Historia' is not defined
'''},
{'date': 'Fri Oct 19 2018 11:50:04.116 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 13
  style=dict(left=180, left = 40, height = 40, width = 170))
                            ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Fri Oct 19 2018 11:51:11.186 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  nemo = Elemento(img=nemo,style=dict(left=180, left = 40, height = 40, width = 170))
                                                     ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Fri Oct 19 2018 11:52:02.817 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  nemo = Elemento(img=nemo,tit="nemo",style=dict(left=180, left = 40, height = 40, width = 170))
                                                                ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Fri Oct 19 2018 11:52:38.464 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  nemo= Elemento(img=nemo,tit="nemo",style=dict(left=180, left = 40, height = 40, width = 170))
                                                               ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Fri Oct 19 2018 11:53:31.671 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  nemo= Elemento(img=nemo,tit="nemo",style=dict(left=180, left = 40, height = 40, width = 170))
                                                               ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Fri Oct 19 2018 11:53:57.832 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  nemo = Elemento(img=nemo,tit="nemo",style=dict(left=180, left = 40, height = 40, width = 170))
                                                                ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Fri Oct 19 2018 11:54:24.256 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  nemo = Elemento(img=nemo,tit="nemo",style=dict(left = 180, left = 40, height = 40, width = 170))
                                                                  ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Fri Oct 19 2018 11:54:51.208 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  nemo = Elemento(img=nemo,tit="nemo",style=dict(left = 150, left = 60, height = 60, width = 150))
                                                                  ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Fri Oct 19 2018 11:55:22.856 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  nemo = Elemento(img=nemo,tit="nemo",style=dict(left = 150, left = 60, height = 60, width = 150))
                                                                  ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Fri Oct 19 2018 11:56:58.952 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  nemo = Elemento(img=NEMO,tit="NEMO",style=dict(left = 180, left = 40, height = 40, width = 170))
                                                                  ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Fri Oct 19 2018 11:57:26.952 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  nemo = Elemento(img=NEMO,tit="NEMO",style=dict(left = 180, left = 40, height = 40, width = 170))
                                                                  ^
SyntaxError: keyword argument repeated
'''},